### ISSUE TITLE
Django: OperationalError at / attempt to write a readonly database

### ISSUE THREAD

**Issue by Sunag3** [django/djangoproject.com#1053]
Dear Team, we have deployed our Django application on Centos 7 Server, its working fine, but the Admin page and write peration on the data base i am unable to perform, given all necessary permissions to data base file and also parent directory.
Server has SELinux is enabled for security policies, i have tried giving the httpd unified as 1, but also not worked

PFB details

Request Method: | POST
-- | --
http://192.168.225.45/
3.1
OperationalError
attempt to write a readonly database
/home/www/project/venv/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py, line 413, in execute
/usr/local/bin/python3
3.6.9

Environment:

Request Method: POST
Request URL: http://192.168.225.45/

Django Version: 3.1
Python Version: 3.6.9
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'testapp']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']

Traceback (most recent call last):
  File "/home/www/project/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/www/project/venv/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)

The above exception (attempt to write a readonly database) was the direct cause of the following exception:
  File "/home/www/project/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/www/project/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/www/project/bookmarks/testapp/views.py", line 14, in CandidateView
    form.save(commit=True)
  File "/home/www/project/venv/lib/python3.6/site-packages/django/forms/models.py", line 460, in save
    self.instance.save()
  File "/home/www/project/venv/lib/python3.6/site-packages/django/db/models/base.py", line 751, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/www/project/venv/lib/python3.6/site-packages/django/db/models/base.py", line 789, in save_base
    force_update, using, update_fields,
  File "/home/www/project/venv/lib/python3.6/site-packages/django/db/models/base.py", line 892, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/home/www/project/venv/lib/python3.6/site-packages/django/db/models/base.py", line 932, in _do_insert
    using=using, raw=raw,
  File "/home/www/project/venv/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/www/project/venv/lib/python3.6/site-packages/django/db/models/query.py", line 1249, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/home/www/project/venv/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1395, in execute_sql
    cursor.execute(sql, params)
  File "/home/www/project/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/home/www/project/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/www/project/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/www/project/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/www/project/venv/lib/python3.6/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/www/project/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/www/project/venv/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)

Exception Type: OperationalError at /
Exception Value: attempt to write a readonly database

Please help, it will be very helpfull for me

**Comment by carltongibson** [comment]
Sorry, this is not a support channel.
