### ISSUE TITLE
mysql client not working on m1 

### ISSUE THREAD

**Issue by SalishKumar** [django/djangoproject.com#1145]
I have  installed native m1 python 3.9, project working perfectly with sqlite but when I switch database to mysql although I have downloaded mysql client 
I get below error
(venv) (base) salishkumar@Salishs-MacBook-Pro tiffinwala % python3 manage.py makemigrations
Traceback (most recent call last):
  File "/Users/salishkumar/backend/tiffinwala/venv/lib/python3.9/site-packages/MySQLdb/__init__.py", line 18, in <module>
    from . import _mysql
ImportError: dlopen(/Users/salishkumar/backend/tiffinwala/venv/lib/python3.9/site-packages/MySQLdb/_mysql.cpython-39-darwin.so, 0x0002): symbol not found in flat namespace '_mysql_affected_rows'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/salishkumar/backend/tiffinwala/manage.py", line 22, in <module>
    main()
  File "/Users/salishkumar/backend/tiffinwala/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/Users/salishkumar/backend/tiffinwala/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 425, in execute_from_command_line
    utility.execute()
  File "/Users/salishkumar/backend/tiffinwala/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute
    django.setup()
  File "/Users/salishkumar/backend/tiffinwala/venv/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/salishkumar/backend/tiffinwala/venv/lib/python3.9/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/Users/salishkumar/backend/tiffinwala/venv/lib/python3.9/site-packages/django/apps/config.py", line 300, in import_models
    self.models_module = import_module(models_module_name)
  File "/Users/salishkumar/opt/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/salishkumar/backend/tiffinwala/venv/lib/python3.9/site-packages/django/contrib/auth/models.py", line 3, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/Users/salishkumar/backend/tiffinwala/venv/lib/python3.9/site-packages/django/contrib/auth/base_user.py", line 47, in <module>
    class AbstractBaseUser(models.Model):
  File "/Users/salishkumar/backend/tiffinwala/venv/lib/python3.9/site-packages/django/db/models/base.py", line 122, in __new__
    new_class.add_to_class('_meta', Options(meta, app_label))
  File "/Users/salishkumar/backend/tiffinwala/venv/lib/python3.9/site-packages/django/db/models/base.py", line 326, in add_to_class
    value.contribute_to_class(cls, name)
  File "/Users/salishkumar/backend/tiffinwala/venv/lib/python3.9/site-packages/django/db/models/options.py", line 207, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "/Users/salishkumar/backend/tiffinwala/venv/lib/python3.9/site-packages/django/utils/connection.py", line 15, in __getattr__
    return getattr(self._connections[self._alias], item)
  File "/Users/salishkumar/backend/tiffinwala/venv/lib/python3.9/site-packages/django/utils/connection.py", line 62, in __getitem__
    conn = self.create_connection(alias)
  File "/Users/salishkumar/backend/tiffinwala/venv/lib/python3.9/site-packages/django/db/utils.py", line 204, in create_connection
    backend = load_backend(db['ENGINE'])
  File "/Users/salishkumar/backend/tiffinwala/venv/lib/python3.9/site-packages/django/db/utils.py", line 111, in load_backend
    return import_module('%s.base' % backend_name)
  File "/Users/salishkumar/opt/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/salishkumar/backend/tiffinwala/venv/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 15, in <module>
    import MySQLdb as Database
  File "/Users/salishkumar/backend/tiffinwala/venv/lib/python3.9/site-packages/MySQLdb/__init__.py", line 24, in <module>
    version_info, _mysql.version_info, _mysql.__file__
NameError: name '_mysql' is not defined

**Comment by felixxm** [comment]
This is the issue tracker for the djangoproject.com website. Please see [TicketClosingReasons/UseSupportChannels](https://code.djangoproject.com/wiki/TicketClosingReasons/UseSupportChannels) for ways to get help with Django usage.
