### ISSUE TITLE
Can't apply fundraising migration 34 due to pending trigger events

### ISSUE THREAD

**Issue by timgraham** [django/djangoproject.com#498]
```
Running migrations:
  Rendering model states... DONE
  Applying fundraising.0016_campaign... OK
  Applying fundraising.0017_auto_20150209_1405... OK
  Applying fundraising.0018_auto_20150209_1424... OK
  Applying fundraising.0019_data_migration_for_campaign... OK
  Applying fundraising.0020_auto_20150209_1633... OK
  Applying fundraising.0021_auto_20150209_1704... OK
  Applying fundraising.0022_auto_20150211_0341... OK
  Applying fundraising.0023_donation_stripe_subscription_id... OK
  Applying fundraising.0024_djangohero_hero_type... OK
  Applying fundraising.0025_auto_20150419_0655... OK
  Applying fundraising.0026_auto_20150419_0727... OK
  Applying fundraising.0027_auto_20150419_0757... OK
  Applying fundraising.0028_auto_20150419_0758... OK
  Applying fundraising.0029_donation_interval... OK
  Applying fundraising.0030_auto_20150604_0608... OK
  Applying fundraising.0031_auto_20150604_0813... OK
  Applying fundraising.0032_auto_20150604_0813... OK
  Applying fundraising.0033_auto_20150611_0750... OK
  Applying fundraising.0034_auto_20150702_0241...Traceback (most recent call last):
  File "/home/tim/.virtualenvs/djangoproject-1.8/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
psycopg2.OperationalError: cannot ALTER TABLE "fundraising_donation" because it has pending trigger events
```
cc @danielroseman

By the way, I finish the Django 1.8 update and merged it to this branch, but didn't create the merge migration yet in case we need to split up migration 34.

**Comment by charettes** [comment]
Do you on which column alteration it is failing?

Migration 33 is updating donations but it should be run in a different transaction if I'm not mistaken. Did you try upgrading to 33 and then to 34?

**Comment by timgraham** [comment]
Here's the sequence of queries (last one fails):
```
ALTER COLUMN "stripe_customer_id" SET DEFAULT %s
UPDATE "fundraising_djangohero" SET "stripe_customer_id" = %s WHERE "stripe_customer_id" IS NULL
ALTER TABLE "fundraising_djangohero" ALTER COLUMN "stripe_customer_id" SET NOT NULL
ALTER TABLE "fundraising_djangohero" ALTER COLUMN "stripe_customer_id" DROP DEFAULT
ALTER TABLE "fundraising_donation" ALTER COLUMN "interval" SET DEFAULT %s
UPDATE "fundraising_donation" SET "interval" = %s WHERE "interval" IS NULL
ALTER TABLE "fundraising_donation" ALTER COLUMN "interval" SET NOT NULL
ALTER TABLE "fundraising_donation" ALTER COLUMN "interval" DROP DEFAULT
ALTER TABLE "fundraising_donation" ALTER COLUMN "receipt_email" SET DEFAULT %s
UPDATE "fundraising_donation" SET "receipt_email" = %s WHERE "receipt_email" IS NULL
ALTER TABLE "fundraising_donation" ALTER COLUMN "receipt_email" SET NOT NULL
ALTER TABLE "fundraising_donation" ALTER COLUMN "receipt_email" DROP DEFAULT
ALTER TABLE "fundraising_donation" ALTER COLUMN "stripe_customer_id" SET DEFAULT %s
UPDATE "fundraising_donation" SET "stripe_customer_id" = %s WHERE "stripe_customer_id" IS NULL
ALTER TABLE "fundraising_donation" ALTER COLUMN "stripe_customer_id" SET NOT NULL
ALTER TABLE "fundraising_donation" ALTER COLUMN "stripe_customer_id" DROP DEFAULT
ALTER TABLE "fundraising_donation" ALTER COLUMN "stripe_subscription_id" SET DEFAULT %s
UPDATE "fundraising_donation" SET "stripe_subscription_id" = %s WHERE "stripe_subscription_id" IS NULL
ALTER TABLE "fundraising_donation" ALTER COLUMN "stripe_subscription_id" SET NOT NULL
```
I guess we need a separate migration to set null values to empty strings (which seems like a bug in Django), although I'm surprised it hasn't been reported.

**Comment by danielroseman** [comment]
This appears to be a bug with migrations that change multiple fields from null=True to null=False. I'll push a PR that splits migration 34 into multiple files, and will also raise a ticket in Django itself.

**Comment by danielroseman** [comment]
Looks like our comments just crossed. Yes I had just come to the same conclusion, PR coming shortly.

**Comment by timgraham** [comment]
Fixed by 80e90eda9a94ebfc8a7a34848796ddd7704bf0a1.

**Comment by angoybu** [comment]
Don't know if I should comment here or create a new issue, but I just had the very same problem with Django==1.11.14.

had three fields in a model that where originally like so:
```
    address = models.CharField(max_length=200, null=True, blank=True)
    phone = models.CharField(max_length=50, null=True, blank=True)
    city = models.CharField(max_length=150, null=True, blank=True)
```
Then I changed them to
```
    address = models.CharField(max_length=200, default='', blank=True)
    phone = models.CharField(max_length=50, default='', blank=True)
    city = models.CharField(max_length=150, default='', blank=True)
```
and generated the following migration
```
    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='address',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='city',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
```
when trying to apply the migrations got the following error:
```
Operations to perform:
  Target specific migration: 0003_auto_20181213_1414, from usuario
Running migrations:
  Applying usuario.0003_auto_20181213_1414...Traceback (most recent call last):
  File "D:\Users\andres\Girolabs\infoparaguay\venv\lib\site-packages\django\db\backends\utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
psycopg2.OperationalError: no se puede hacer ALTER TABLE en «usuario_perfil» porque tiene eventos de disparador pendientes
```

Again, please let me know if I should create a new issue or if it's OK to post it here since it's related

**Comment by charettes** [comment]
@angoybu this is a bug tracker for the djangoproject.com website. You'll want to come up with a simplified and reproducible test case against the latest version of Django (2.1 as I write this comment) and [file a new ticket on Trac](https://code.djangoproject.com/newticket) once you came up with it. Make sure to include your version of PostgreSQL as well.
