### ISSUE TITLE
Deploying the website on the local computer. The problem with Elasticsearch

### ISSUE THREAD

**Issue by qwwa** [django/djangoproject.com#526]
Hi, I tried to run locally djangoproject.com, but when you run the command `./manage.py update_docs` I get the error:
```
Updating en/dev...
HEAD is now at c14b6b5 Documented auth's login/logout function parameters.
Removing django/__pycache__/
Removing django/apps/__pycache__/
Removing django/conf/__pycache__/
Removing django/conf/urls/__pycache__/
Removing django/contrib/__pycache__/
Removing django/contrib/admin/__pycache__/
Removing django/contrib/admin/templatetags/__pycache__/
Removing django/contrib/admin/views/__pycache__/
Removing django/contrib/auth/__pycache__/
Removing django/contrib/contenttypes/__pycache__/
Removing django/contrib/flatpages/__pycache__/
Removing django/contrib/gis/__pycache__/
Removing django/contrib/gis/admin/__pycache__/
Removing django/contrib/gis/db/__pycache__/
Removing django/contrib/gis/db/models/__pycache__/
Removing django/contrib/gis/forms/__pycache__/
Removing django/contrib/gis/gdal/__pycache__/
Removing django/contrib/gis/gdal/prototypes/__pycache__/
Removing django/contrib/gis/geoip/__pycache__/
Removing django/contrib/gis/geoip2/__pycache__/
Removing django/contrib/gis/geometry/__pycache__/
Removing django/contrib/gis/geometry/backend/__pycache__/
Removing django/contrib/gis/geos/__pycache__/
Removing django/contrib/gis/geos/prototypes/__pycache__/
Removing django/contrib/gis/utils/__pycache__/
Removing django/contrib/messages/__pycache__/
Removing django/contrib/messages/storage/__pycache__/
Removing django/contrib/postgres/__pycache__/
Removing django/contrib/postgres/aggregates/__pycache__/
Removing django/contrib/postgres/fields/__pycache__/
Removing django/contrib/postgres/forms/__pycache__/
Removing django/contrib/redirects/__pycache__/
Removing django/contrib/sessions/__pycache__/
Removing django/contrib/sitemaps/__pycache__/
Removing django/contrib/sites/__pycache__/
Removing django/contrib/staticfiles/__pycache__/
Removing django/contrib/syndication/__pycache__/
Removing django/core/__pycache__/
Removing django/core/cache/__pycache__/
Removing django/core/cache/backends/__pycache__/
Removing django/core/checks/__pycache__/
Removing django/core/checks/compatibility/__pycache__/
Removing django/core/checks/security/__pycache__/
Removing django/core/files/__pycache__/
Removing django/core/handlers/__pycache__/
Removing django/core/mail/__pycache__/
Removing django/core/management/__pycache__/
Removing django/core/serializers/__pycache__/
Removing django/core/servers/__pycache__/
Removing django/db/__pycache__/
Removing django/db/backends/__pycache__/
Removing django/db/backends/base/__pycache__/
Removing django/db/migrations/__pycache__/
Removing django/db/migrations/operations/__pycache__/
Removing django/db/models/__pycache__/
Removing django/db/models/fields/__pycache__/
Removing django/db/models/sql/__pycache__/
Removing django/dispatch/__pycache__/
Removing django/forms/__pycache__/
Removing django/http/__pycache__/
Removing django/middleware/__pycache__/
Removing django/template/__pycache__/
Removing django/template/backends/__pycache__/
Removing django/template/loaders/__pycache__/
Removing django/test/__pycache__/
Removing django/utils/__pycache__/
Removing django/utils/translation/__pycache__/
Removing django/views/__pycache__/
Removing django/views/decorators/__pycache__/
Removing django/views/generic/__pycache__/
Removing docs/_ext/__pycache__/
Already up-to-date.
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/user/projects/djangoproject.com/env/lib/python3.4/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/user/projects/djangoproject.com/env/lib/python3.4/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/user/projects/djangoproject.com/env/lib/python3.4/site-packages/django/core/management/base.py", line 393, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/user/projects/djangoproject.com/env/lib/python3.4/site-packages/django/core/management/base.py", line 444, in execute
    output = self.handle(*args, **options)
  File "/home/user/projects/djangoproject.com/env/lib/python3.4/site-packages/django/core/management/base.py", line 660, in handle
    return self.handle_noargs(**options)
  File "/home/user/projects/djangoproject.com/docs/management/commands/update_docs.py", line 202, in handle_noargs
    DocumentDocType.index_object(doc)
  File "/home/user/projects/djangoproject.com/docs/search.py", line 95, in index_object
    return cls.from_django(obj).save()
  File "/home/user/projects/djangoproject.com/env/lib/python3.4/site-packages/elasticsearch_dsl/document.py", line 197, in save
    return meta['created']
KeyError: 'created'
```

Elasticsearch works, because localhost:9200 answers
```
{
  "ok" : true,
  "status" : 200,
  "name" : "Schemer",
  "version" : {
    "number" : "0.90.7",
    "build_hash" : "36897d07dadcb70886db7f149e645ed3d44eb5f2",
    "build_timestamp" : "2013-11-13T12:06:54Z",
    "build_snapshot" : false,
    "lucene_version" : "4.5.1"
  },
  "tagline" : "You Know, for Search"
}
```

Python 3.4, Ububntu 14.04

**Comment by timgraham** [comment]
Could you please try a more recent version of elasticsearch? I have no trouble with:
```
{
  "status" : 200,
  "name" : "Fixer",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "1.5.2",
    "build_hash" : "62ff9868b4c8a0c45860bebb259e21980778ab1c",
    "build_timestamp" : "2015-04-27T09:21:06Z",
    "build_snapshot" : false,
    "lucene_version" : "4.10.4"
  },
  "tagline" : "You Know, for Search"
}
```

**Comment by qwwa** [comment]
It's works, thank you. Solved.
