### ISSUE TITLE
Trouble updating to libsass 0.8.3.

### ISSUE THREAD

**Issue by timgraham** [django/djangoproject.com#530]
After updating and trying to deploy, `collectstatic` fails:
```
:stderr: Post-processing 'css/output-ie.css' failed!

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/www/www/venv/lib/python3.4/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/www/www/venv/lib/python3.4/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/www/www/venv/lib/python3.4/site-packages/django/core/management/base.py", line 393, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/www/www/venv/lib/python3.4/site-packages/django/core/management/base.py", line 444, in execute
    output = self.handle(*args, **options)
  File "/home/www/www/venv/lib/python3.4/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 168, in handle
    collected = self.collect()
  File "/home/www/www/venv/lib/python3.4/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 120, in collect
    raise processed
  File "/home/www/www/venv/lib/python3.4/site-packages/django/contrib/staticfiles/storage.py", line 245, in post_process
    content = pattern.sub(converter, content)
  File "/home/www/www/venv/lib/python3.4/site-packages/django/contrib/staticfiles/storage.py", line 184, in converter
    hashed_url = self.url(unquote(joined_result), force=True)
  File "/home/www/www/venv/lib/python3.4/site-packages/django/contrib/staticfiles/storage.py", line 131, in url
    hashed_name = self.stored_name(clean_name)
  File "/home/www/www/venv/lib/python3.4/site-packages/django/contrib/staticfiles/storage.py", line 280, in stored_name
    cache_name = self.clean_name(self.hashed_name(name))
  File "/home/www/www/venv/lib/python3.4/site-packages/django/contrib/staticfiles/storage.py", line 94, in hashed_name
    (clean_name, self))
ValueError: The file 'img/'+$name+'.png' could not be found with <django.contrib.staticfiles.storage.ManifestStaticFilesStorage object at 0x7fce99dd5358>.
```

**Comment by timgraham** [comment]
Updated to libsass==0.9.2 in 1075f09900b7933e2de93fc881d92096764ea788 without a problem so I guess this may have been a bug in libsass.
