### ISSUE TITLE
Docs build error: "Cannot delete indices that are being snapshotted"

### ISSUE THREAD

**Issue by timgraham** [django/djangoproject.com#737]
Sometimes [`DocumentDocType.alias_to_main_index()`](https://github.com/django/djangoproject.com/blob/7e188d8ee5d403a1e530dcabddd6685421b5a298/docs/search.py#L159-L178) crashes like this:
```
DELETE https://7cd8f7a21dbf68934d42d468910c155e-us-east-1.foundcluster.com:9243/docs-2017-02-12t18%3A00%3A09.916080 [status:400 request:0.178s]
Traceback (most recent call last):
...
  File "/home/www/www/src/docs/management/commands/update_index.py", line 28, in handle
    DocumentDocType.alias_to_main_index(new_index_name)
  File "/home/www/www/src/docs/search.py", line 178, in alias_to_main_index
    client.indices.delete(old_index_name)
  File "/home/www/www/venv/lib/python3.5/site-packages/elasticsearch/client/utils.py", line 71, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/home/www/www/venv/lib/python3.5/site-packages/elasticsearch/client/indices.py", line 200, in delete
    params=params)
  File "/home/www/www/venv/lib/python3.5/site-packages/elasticsearch/transport.py", line 318, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/home/www/www/venv/lib/python3.5/site-packages/elasticsearch/connection/http_urllib3.py", line 127, in perform_request
    self._raise_error(response.status, raw_data)
  File "/home/www/www/venv/lib/python3.5/site-packages/elasticsearch/connection/base.py", line 122, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Cannot delete indices that are being snapshotted: [[docs-2017-02-12t18:00:09.916080/-C5sHfYsTBOA3klBpDfhuw]]. Try again after snapshot finishes or cancel the currently running snapshot.')
```

**Comment by timgraham** [comment]
@HonzaKral, any advice?

**Comment by frankwiles** [comment]
I'm obviously not @HonzaKral but I ran into that once and just had to wait a few minutes until the Snapshot was done and then I could delete it.

**Comment by HonzaKral** [comment]
Just as @frankwiles said - if the index is in the process of being snapshotted, it is protected and you need to wait.

If this is affecting operations you can always skip the delete in this method and have a separate background task that will run periodically and remove any old indices it finds.

**Comment by timgraham** [comment]
We have an hourly cron that rebuilds the docs and reindexes . The failure happens at the end of that process. We could insert a sleep into that script if it's reliable or write a separate clean up job. Anyone have an example script for the latter technique off hand?

**Comment by HonzaKral** [comment]
This might help:
```
def remove_old_indices(prefix=INDEX_PREFIX, keep=2):
    """
    Remove all indices starting with INDEX_PREFIX while keeping only last
    `keep`.
    """
    indices = es.cat.indices(index=prefix + '*', format='json', h='index')
    versions = [int(i['index'][len(prefix):]) for i in indices]
    versions.sort()
    while keep and versions:
        versions.pop()
        keep -= 1
    to_delete = ['%s%d' % (prefix, v) for v in versions]
    if to_delete:
        es.indices.delete(index=to_delete)
```

**Comment by timgraham** [comment]
This error hasn't reoccurred. It seems it was caused by a memory leak bug in Elasticsearch that's been fixed.
