### ISSUE TITLE
Password validation Error with Latin characters

### ISSUE THREAD

**Issue by nairdaus** [django/djangoproject.com#802]
I am using the function 'validate_password (password, new_user)' and I have my settings configured in Spanish, the problem comes when the validate_password function raises an error with the word 'contraseña' and shows me this error:
ValidationError: [u'La contrase\xf1a es demasiado similar a la de nombre de usuario.']
I am using python 2.7 and Django 1.11.4

This is the traceback:

```
Traceback (most recent call last):
  File "/Users/adrianmansilla/Documents/sisgos/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/adrianmansilla/Documents/sisgos/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/adrianmansilla/Documents/sisgos/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/adrianmansilla/Documents/sisgos/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/adrianmansilla/Documents/sisgos/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/Users/adrianmansilla/Documents/sisgos/sisgos/company/views.py", line 129, in new_user
    validate_password(password, new_user)
  File "/Users/adrianmansilla/Documents/sisgos/venv/lib/python2.7/site-packages/django/contrib/auth/password_validation.py", line 56, in validate_password
    raise ValidationError(errors)
ValidationError: [u'La contrase\xf1a es demasiado similar a la de nombre de usuario.']
```

**Comment by timgraham** [comment]
This is the issue tracker for the djangoproject.com website.  To report bugs in Django, use https://code.djangoproject.com/, however, I'm sure this is a bug in Django -- `\xf1` is the ñ character. Can you explain the issue in more detail and propose a fix?
