### ISSUE TITLE
Django 1.11 upgrade -> runserver error with user related field `groups` is throwing an attribute error

### ISSUE THREAD

**Issue by eneumann** [django/djangoproject.com#909]
I'm currently upgrading from Django 1.10 to 1.11. I've addressed all deprecation issues and everything is working fine, our app is running on gunicorn and django shell works. However, runserver is throwing an error that I can't seem to sort out. Looks like it's happening on the related groups field to the user model. We are using a custom user model which was working fine in 1.10. Below is the stack trace. Appreciate any help in getting this resolved. Cheers!

error in db/models/fields/related.py _check_table_uniqueness()

Unhandled exception in thread started by <function wrapper at 0x7f6d8b8358c0>
Traceback (most recent call last):
  File "/home/manzama/.virtualenvs/manzama/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 227, in wrapper
    fn(*args, **kwargs)
  File "/home/manzama/.virtualenvs/manzama/local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 125, in inner_run
    self.check(display_num_errors=True)
  File "/home/manzama/.virtualenvs/manzama/local/lib/python2.7/site-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/manzama/.virtualenvs/manzama/local/lib/python2.7/site-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/manzama/.virtualenvs/manzama/local/lib/python2.7/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/manzama/.virtualenvs/manzama/local/lib/python2.7/site-packages/django/core/checks/model_checks.py", line 30, in check_all_models
    errors.extend(model.check(**kwargs))
  File "/home/manzama/.virtualenvs/manzama/local/lib/python2.7/site-packages/django/db/models/base.py", line 1282, in check
    errors.extend(cls._check_fields(**kwargs))
  File "/home/manzama/.virtualenvs/manzama/local/lib/python2.7/site-packages/django/db/models/base.py", line 1359, in _check_fields
    errors.extend(field.check(from_model=cls, **kwargs))
  File "/home/manzama/.virtualenvs/manzama/local/lib/python2.7/site-packages/django/db/models/fields/related.py", line 1195, in check
    errors.extend(self._check_table_uniqueness(**kwargs))
  File "/home/manzama/.virtualenvs/manzama/local/lib/python2.7/site-packages/django/db/models/fields/related.py", line 1446, in _check_table_uniqueness
    for model in self.opts.apps.get_models(include_auto_created=True)
  File "/home/manzama/.virtualenvs/manzama/local/lib/python2.7/site-packages/django/db/models/fields/related.py", line 1447, in <dictcomp>
    if model != self.remote_field.through and model._meta.managed
AttributeError: 'ModelOptions' object has no attribute 'managed'

**Comment by charettes** [comment]
This issue tracker is for djangoproject.com itself and not the Django framework.

Also please avoid [cross posting to multiple platforms](https://code.djangoproject.com/ticket/30384) and refer to the documentation [to get help](https://docs.djangoproject.com/en/2.2/faq/help/#how-do-i-do-x-why-doesn-t-y-work-where-can-i-go-to-get-help).

**Comment by eneumann** [comment]
Hello Simon,

Thanks, will do.

Eric Neumann
Senior Software Engineer

[image: Manzama Logo] <http://www.manzama.com/>

Check out our Use Cases <http://manzama.com/use-cases/>.

US & CAN Office: +1 (541) 306 3271 <+15413063271> | UK Office: +44 (0)7545
318 346 <+4407545318346> | AUS Office: +61 (0) 2 8417 2339 <+610284172339>

LinkedIn  <http://www.linkedin.com/company/manzama>| Twitter
<https://twitter.com/ManzamaInc>| Facebook
<http://www.facebook.com/manzamainc>| YouTube
<https://www.youtube.com/channel/UCBo3QoqewyNoo7HiT_BFuRw>
