### ISSUE TITLE
_frozen_importlib._DeadlockError: deadlock detected by _ModuleLock('django.test.signals')

### ISSUE THREAD

**Issue by luktar** [django/djangoproject.com#913]
Django crashing because of a deadlock 8 / 10 times.
After changing django to version 2.1.7 it works perfectly (but it's not a case I suppose :) ).

Mac OSX 10.14.4
Python 3.7

requirements.txt:

djangorestframework == 3.9.4
markdown == 3.1
django-filter == 2.1.0
**django == 2.2.1**
psycopg2-binary == 2.8.2
djangorestframework-camel-case == 1.0.3
django-cors-headers == 3.0.1
six == 1.12.0
django-ckeditor == 5.7.1

Log:

^C[user-name:~/Dev/folder/intranet/GIT/project-name/back] [venv] feature/init_web_api(+33/-1)+* ± **python manage.py runserver**

Watching for file changes with StatReloader
Performing system checks...

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/Users/user-name/Dev/folder/intranet/GIT/project-name/back/venv/lib/python3.7/site-packages/django/template/utils.py", line 66, in __getitem__
    return self._engines[alias]
KeyError: 'django'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/user-name/Dev/folder/intranet/GIT/project-name/back/venv/lib/python3.7/site-packages/django/utils/autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "/Users/user-name/Dev/folder/intranet/GIT/project-name/back/venv/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    self.check(display_num_errors=True)
  File "/Users/user-name/Dev/folder/intranet/GIT/project-name/back/venv/lib/python3.7/site-packages/django/core/management/base.py", line 390, in check
    include_deployment_checks=include_deployment_checks,
  File "/Users/user-name/Dev/folder/intranet/GIT/project-name/back/venv/lib/python3.7/site-packages/django/core/management/base.py", line 377, in _run_checks
    return checks.run_checks(**kwargs)
  File "/Users/user-name/Dev/folder/intranet/GIT/project-name/back/venv/lib/python3.7/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/Users/user-name/Dev/folder/intranet/GIT/project-name/back/venv/lib/python3.7/site-packages/django/contrib/admin/checks.py", line 79, in check_dependencies
    for engine in engines.all():
  File "/Users/user-name/Dev/folder/intranet/GIT/project-name/back/venv/lib/python3.7/site-packages/django/template/utils.py", line 90, in all
    return [self[alias] for alias in self]
  File "/Users/user-name/Dev/folder/intranet/GIT/project-name/back/venv/lib/python3.7/site-packages/django/template/utils.py", line 90, in <listcomp>
    return [self[alias] for alias in self]
  File "/Users/user-name/Dev/folder/intranet/GIT/project-name/back/venv/lib/python3.7/site-packages/django/template/utils.py", line 81, in __getitem__
    engine = engine_cls(params)
  File "/Users/user-name/Dev/folder/intranet/GIT/project-name/back/venv/lib/python3.7/site-packages/django/template/backends/django.py", line 25, in __init__
    options['libraries'] = self.get_templatetag_libraries(libraries)
  File "/Users/user-name/Dev/folder/intranet/GIT/project-name/back/venv/lib/python3.7/site-packages/django/template/backends/django.py", line 43, in get_templatetag_libraries
    libraries = get_installed_libraries()
  File "/Users/user-name/Dev/folder/intranet/GIT/project-name/back/venv/lib/python3.7/site-packages/django/template/backends/django.py", line 108, in get_installed_libraries
    for name in get_package_libraries(pkg):
  File "/Users/user-name/Dev/folder/intranet/GIT/project-name/back/venv/lib/python3.7/site-packages/django/template/backends/django.py", line 121, in get_package_libraries
    module = import_module(entry[1])
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/user-name/Dev/folder/intranet/GIT/project-name/back/venv/lib/python3.7/site-packages/rest_framework/templatetags/rest_framework.py", line 15, in <module>
    from rest_framework.renderers import HTMLFormRenderer
  File "/Users/user-name/Dev/folder/intranet/GIT/project-name/back/venv/lib/python3.7/site-packages/rest_framework/renderers.py", line 20, in <module>
    from django.test.client import encode_multipart
  File "/Users/user-name/Dev/folder/intranet/GIT/project-name/back/venv/lib/python3.7/site-packages/django/test/client.py", line 23, in <module>
    from django.test import signals
  File "<frozen importlib._bootstrap>", line 980, in _find_and_load
  File "<frozen importlib._bootstrap>", line 149, in __enter__
  File "<frozen importlib._bootstrap>", line 94, in acquire
_frozen_importlib._DeadlockError: deadlock detected by _ModuleLock('django.test.signals') at 4546635928

**Comment by felixxm** [comment]
This is the issue tracker for the djangoproject.com website. Please see [TicketClosingReasons/UseSupportChannels](https://code.djangoproject.com/wiki/TicketClosingReasons/UseSupportChannels) for ways to get help with Django usage.

You can also check a ticket [30352](https://code.djangoproject.com/ticket/30352) with similar description.
