### ISSUE TITLE
Failing to save model with foreign key

### ISSUE THREAD

**Issue by bangbangphil** [django/djangoproject.com#937]
I have a simple one-to-many relationship and I am trying to understand why my test case of instantiation and saving to database is failing. I'm trying to follow a pattern where I gather all data in my models instance in a first step, and then saving all to database in a second. I am facing the issue where a model with a foreign key relation has to have its related model not only saved beforehands (that I can understand), but also its foreign model attribute must be explicitly set after being saved (that I don't understand). I have made two simple test cases to implement both behaviors. Here are the models in a one-to many relationship :
```
class Document(models.Model):
    pass

class Section(models.Model):
    document = models.ForeignKey('Document',on_delete=models.CASCADE)
```
Here is the working test case of model creation, as explained un django doc (in manage.py shell):
```
>>> doc = models.Document()
>>> doc.save()
>>> section = models.Section(document=doc)
>>> section.document
<Document: Document object (5)>
>>> section.save()
>>> 
```
And here is the test case that fails.
```
>>> doc = models.Document()
>>> section = models.Section(document=doc)
>>> section.document
<Document: Document object (None)>
>>> doc.save()
>>> section.document
<Document: Document object (6)>
>>> section.save()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    section.save()
  File "/home/philippe/.local/lib/python3.6/site-packages/django/db/models/base.py", line 741, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/philippe/.local/lib/python3.6/site-packages/django/db/models/base.py", line 779, in save_base
    force_update, using, update_fields,
  File "/home/philippe/.local/lib/python3.6/site-packages/django/db/models/base.py", line 870, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/philippe/.local/lib/python3.6/site-packages/django/db/models/base.py", line 908, in _do_insert
    using=using, raw=raw)
  File "/home/philippe/.local/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/philippe/.local/lib/python3.6/site-packages/django/db/models/query.py", line 1186, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/philippe/.local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1335, in execute_sql
    cursor.execute(sql, params)
  File "/home/philippe/.local/lib/python3.6/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/home/philippe/.local/lib/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/philippe/.local/lib/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/philippe/.local/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/philippe/.local/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 76, in execute
    raise utils.IntegrityError(*tuple(e.args))
django.db.utils.IntegrityError: (1048, "Column 'document_id' cannot be null")
>>> section.document
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    section.document
  File "/home/philippe/.local/lib/python3.6/site-packages/django/db/models/fields/related_descriptors.py", line 189, in __get__
    "%s has no %s." % (self.field.model.__name__, self.field.name)
diagnosisrank.models.common.Section.document.RelatedObjectDoesNotExist: Section has no document.
>>> 
```
The only difference with the working test case is that the related Document model is not saved before instantiating the Section model. However, after saving the Document model, we see that the related document model of the Section model is pointing to the saved Document (its id is set). But when trying to save the Section, the related id is not set and the related model is lost. Why is that? Why do the related Document model instance must be assigned to the Section only after being saved?

Thanks for any help or insight!

Phil

**Comment by felixxm** [comment]
This is the issue tracker for the djangoproject.com website. Bugs should be reported on [Trac](https://code.djangoproject.com/), however this specific issue is already solved, see https://github.com/django/django/commit/519016e5f25d7c0a040015724f9920581551cab0.
